openapi: 3.1.2
info:
  contact:
    name: OpenCage GmbH
    url: https://opencagedata.com/contact
  version: 1.1.0
  termsOfService: https://opencagedata.com/terms
  title: OpenCage Geocoder
  description: >
    Worldwide forward and reverse geocoding with open data.

    # Rate Limiting

    Responses to subscription customers do NOT contain the `rate` element of the response body or `X-Ratelimit` HTTP headers, because they do not face hard limits. 

  x-origin:
    format: openapi
    url: https://opencagedata.com/openapi.yaml
    version: 3.1.2
  x-logo:
    url: https://opencagedata.com/opencagelogo-green.png

externalDocs:
  description: OpenCage Geocoder Website
  url: https://opencagedata.com/api
    
servers:
  - url: https://api.opencagedata.com/geocode/v1

security: 
  - ApiKeyAuth: []

paths:
  /json:
    $ref: paths/json.yaml
  /xml:
    $ref: paths/xml.yaml
  /geojson:
    $ref: paths/geojson.yaml

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: key 
      description: 30 character long, alphanumeric string unique to your account. See https://opencagedata.com/api#required-params
